apiVersion: v1
kind: ReplicationController
metadata:
  name: ark-super-silly-fun-land
  labels:
    name: ark-super-silly-fun-land
    state: serving
spec:
  replicas: 1
  selector:
    name: ark-super-silly-fun-land
  template:
    metadata:
      labels:
        name: ark-super-silly-fun-land
    spec:
      containers:
      - name: ark
        image: quay.io/jonathanporta/ogs-servers-ark-super-silly-fun-land
        imagePullPolicy: Always
        ports:
        - containerPort: 27015
          protocol: UDP
        - containerPort: 7777
          protocol: UDP
        - containerPort: 7778
          protocol: UDP
        - containerPort: 32330
          protocol: UDP
        - containerPort: 27015
          protocol: TCP
        - containerPort: 7777
          protocol: TCP
        - containerPort: 7778
          protocol: TCP
        - containerPort: 32330
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
