apiVersion: v1
kind: ReplicationController
metadata:
  name: hurtworld-hurtcoast
  labels:
    name: hurtworld-hurtcoast
    state: serving
spec:
  replicas: 1
  selector:
    name: hurtworld-hurtcoast
  template:
    metadata:
      labels:
        name: hurtworld-hurtcoast
    spec:
      containers:
      - name: hurtworld-hurtcoast-container
        image: quay.io/jonathanporta/ogs-servers-hurtworld-hurtcoast
        imagePullPolicy: Always
        ports:
        - containerPort: 12871
          protocol: UDP
        - containerPort: 12881
          protocol: UDP
      dnsPolicy: ClusterFirst
      restartPolicy: Always



    # spec:
    #   containers:
    #   - name: worker
    #     image: gcr.io/google_samples/gb-redisslave:v1
    #     env:
    #     - name: GET_HOSTS_FROM
    #       value: dns
    #       # If your cluster config does not include a dns service, then to
    #       # instead access an environment variable to find the master
    #       # service's host, comment out the 'value: dns' line above, and
    #       # uncomment the line below.
    #       # value: env
    #     ports:
    #     - containerPort: 6379
