apiVersion: v1
kind: Service
metadata:
  name: hurtworld-hurtcoast
  labels:
    state: serving
  namespace: default
spec:
  type: NodePort
  ports:
  - name: client
    port: 12871
    targetPort: 12871
    protocol: UDP
    nodePort: 30358
  - name: query
    port: 12881
    targetPort: 12881
    protocol: UDP
    nodePort: 30846
  selector:
    app: hurtworld-hurtcoast
