apiVersion: v1
kind: Service
metadata:
  name: ark-super-silly-fun-land
  labels:
    state: serving
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: client-udp
    port: 27015
    targetPort: 27015
    protocol: UDP
  # - name: client-tcp
  #   port: 27015
  #   targetPort: 27015
  #   protocol: TCP
  - name: 7777-udp
    port: 7777
    targetPort: 7777
    protocol: UDP
  # - name: 7777-tcp
  #   port: 7777
  #   targetPort: 7777
  #   protocol: TCP
  - name: 7778-udp
    port: 7778
    targetPort: 7778
    protocol: UDP
  # - name: 7778-tcp
  #   port: 7778
  #   targetPort: 7778
  #   protocol: TCP
  - name: 32330-udp
    port: 32330
    targetPort: 32330
    protocol: UDP
  # - name: 32330-tcp
  #   port: 32330
  #   targetPort: 32330
  #   protocol: TCP
  externalIPs:
  - 45.55.185.119
  selector:
    app: ark-super-silly-fun-land
