apiVersion: v1
kind: Service
metadata:
  name: ark-super-silly-fun-land
  labels:
    state: serving
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 27015
    targetPort: 27015
    protocol: UDP
  - port: 27015
    targetPort: 27015
    protocol: TCP
  - port: 7777
    targetPort: 7777
    protocol: UDP
  - port: 7777
    targetPort: 7777
    protocol: TCP
  - port: 7778
    targetPort: 7778
    protocol: UDP
  - port: 7778
    targetPort: 7778
    protocol: TCP
  - port: 32330
    targetPort: 32330
    protocol: UDP
  - port: 32330
    targetPort: 32330
    protocol: TCP
  selector:
    app: ark-super-silly-fun-land
